



const quotes = [
  { quote: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { quote: "If you are working on something exciting, it will keep you motivated.", author: "Steve Jobs" },
  { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
  { quote: "Your limitation—it’s only your imagination.", author: "Unknown" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { quote: "Dream bigger. Do bigger.", author: "Unknown" },
  { quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { quote: "Do something today that your future self will thank you for.", author: "Unknown" },
  { quote: "Little things make big days.", author: "Unknown" },
  { quote: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
  { quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { quote: "Dream it. Believe it. Build it.", author: "Unknown" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Success is not how high you have climbed, but how you make a difference.", author: "Roy T. Bennett" },
  { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar" },
  { quote: "I never dreamed about success. I worked for it.", author: "Estee Lauder" },
  { quote: "Don’t be pushed around by fears. Be led by dreams.", author: "Roy T. Bennett" },
  { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller" },
  { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { quote: "Opportunities are usually disguised as hard work.", author: "Ann Landers" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "Big journeys begin with small steps.", author: "Unknown" },
  { quote: "Don’t limit your challenges. Challenge your limits.", author: "Unknown" },
  { quote: "When you feel like quitting, remember why you started.", author: "Unknown" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
  { quote: "If you don’t build your dream, someone else will hire you to help them build theirs.", author: "Tony Gaskins" },
  { quote: "Go the extra mile. It’s never crowded.", author: "Unknown" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { quote: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
  { quote: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
  { quote: "Don’t compare yourself with anyone in this world. If you do so, you are insulting yourself.", author: "Bill Gates" },
  { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
  { quote: "Don’t be afraid to fail. Be afraid not to try.", author: "Michael Jordan" },
  { quote: "Do not wait; the time will never be ‘just right.’", author: "Napoleon Hill" },
  { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Don’t downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.", author: "Unknown" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { quote: "If you want something you’ve never had, you must be willing to do something you’ve never done.", author: "Thomas Jefferson" },
  { quote: "Your future is created by what you do today, not tomorrow.", author: "Anonymous" },
  { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { quote: "Some people dream of success while others wake up and work hard at it.", author: "Napoleon Hill" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { quote: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
  { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "Stay away from negative people. They have a problem for every solution.", author: "Albert Einstein" },
  { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "Act like you make a difference. You do.", author: "William James" },
  { quote: "Limit your ‘always’ and your ‘nevers’.", author: "Amy Poehler" },
  { quote: "Nothing is impossible. The word itself says ‘I’m possible!’", author: "Audrey Hepburn" },
  { quote: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { quote: "The bad news is time flies. The good news is you’re the pilot.", author: "Michael Altshuler" },
  { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "Everything has beauty, but not everyone can see.", author: "Confucius" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
  { quote: "Spread love everywhere you go.", author: "Mother Teresa" },
  { quote: "Do what you feel in your heart to be right.", author: "Eleanor Roosevelt" }
];

function generate(){
     let random = quotes[Math.floor(Math.random() * quotes.length)];
     const quote = document.getElementById("quote")
     quote.innerText= random.quote
}
generate()